spring.datasource.url=jdbc:mysql://localhost:3306/fundoonotesdb
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

spring.artemis.mode=embedded

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=guest
spring.rabbitmq.password=${RABBIT_MQ}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaidikchoudhary771@gmail.com
spring.mail.password=${FUNDOO_MAIL}  
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true