create table "department" (
    id bigint generated by default as identity primary key,
    name varchar(100) not null
);

create table "employee" (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(150) not null,
    phone varchar(20),
    salary decimal(12,2),
    department_id bigint,
    constraint fk_employee_department
        foreign key (department_id)
        references "department"(id)
);